#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CODEX_ROOT="${CODEX_ROOT:-${HOME}/.codex}"
INSTALL_ROOT="${CODEX_ROOT}/parts-product-selection-integrations"
APPLY_CONFIG=0

usage() {
  cat <<'EOF'
Usage: install.sh [--apply-config]

Installs the bundled, non-secret Meta and WordPress MCP servers into the
current user's Codex directory and generates a machine-specific config file.

  --apply-config  Back up ~/.codex/config.toml and append the generated MCP
                  blocks when they are not already present.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --apply-config) APPLY_CONFIG=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This installer currently supports macOS only." >&2
  exit 1
fi

if command -v node >/dev/null 2>&1; then
  NODE_BIN="$(command -v node)"
elif [[ -x "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node" ]]; then
  NODE_BIN="/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
else
  echo "Node.js was not found. Install Node.js 20+ or open ChatGPT once." >&2
  exit 1
fi

mkdir -p "${INSTALL_ROOT}/meta-ads-mcp/scripts" "${INSTALL_ROOT}/wordpress"
cp "${ROOT_DIR}/integrations/servers/meta-ads-mcp/scripts/"*.mjs "${INSTALL_ROOT}/meta-ads-mcp/scripts/"
cp "${ROOT_DIR}/integrations/servers/meta-ads-mcp/plugin.json" "${INSTALL_ROOT}/meta-ads-mcp/"
cp "${ROOT_DIR}/integrations/servers/wordpress/server.mjs" "${INSTALL_ROOT}/wordpress/"
cp "${ROOT_DIR}/integrations/installer/configure-keychain.sh" "${INSTALL_ROOT}/"
cp "${ROOT_DIR}/integrations/installer/doctor.sh" "${INSTALL_ROOT}/"
chmod 755 "${INSTALL_ROOT}/meta-ads-mcp/scripts/"*.mjs "${INSTALL_ROOT}/wordpress/server.mjs"
chmod 755 "${INSTALL_ROOT}/"*.sh

CONFIG_DIR="${INSTALL_ROOT}/config"
mkdir -p "${CONFIG_DIR}"
cat > "${CONFIG_DIR}/mcp.toml" <<EOF
# Generated by parts-product-selection. Machine-specific; do not commit.

[mcp_servers.southeastrippa_wordpress]
command = "${NODE_BIN}"
args = ["${INSTALL_ROOT}/wordpress/server.mjs"]
startup_timeout_sec = 30

[mcp_servers.southeastrippa_wordpress.env]
SOUTHEASTRIPPA_WORDPRESS_SITE_URL = "https://www.southeastrippa.us"
SOUTHEASTRIPPA_WORDPRESS_USERNAME = "codex_mcp"
SOUTHEASTRIPPA_WORDPRESS_KEYCHAIN_SERVICE = "codex.southeastrippa.wordpress"
SOUTHEASTRIPPA_WORDPRESS_KEYCHAIN_ACCOUNT = "codex_mcp"
SOUTHEASTRIPPA_RS06_PRODUCT_ID = "162"

[mcp_servers.meta_ads]
command = "${NODE_BIN}"
args = ["${INSTALL_ROOT}/meta-ads-mcp/scripts/meta-ads-mcp.mjs"]
startup_timeout_sec = 30

[mcp_servers.meta_ads.env]
META_AD_ACCOUNT_ID = "act_900524242288960"
META_INSTAGRAM_ACCOUNT_ID = "17841471481136852"
META_PAGE_ID = "495341997002120"
META_GRAPH_API_VERSION = "v25.0"
META_KEYCHAIN_SERVICE = "codex.meta.ads"
META_KEYCHAIN_ACCOUNT = "access-token"
EOF

cat > "${CONFIG_DIR}/meta-ads.json" <<EOF
{
  "mcpServers": {
    "meta-ads": {
      "command": "${NODE_BIN}",
      "args": ["${INSTALL_ROOT}/meta-ads-mcp/scripts/meta-ads-mcp.mjs"],
      "env": {
        "META_AD_ACCOUNT_ID": "act_900524242288960",
        "META_INSTAGRAM_ACCOUNT_ID": "17841471481136852",
        "META_PAGE_ID": "495341997002120",
        "META_GRAPH_API_VERSION": "v25.0",
        "META_KEYCHAIN_SERVICE": "codex.meta.ads",
        "META_KEYCHAIN_ACCOUNT": "access-token"
      }
    }
  }
}
EOF

if [[ "${APPLY_CONFIG}" -eq 1 ]]; then
  CODEX_CONFIG="${CODEX_ROOT}/config.toml"
  mkdir -p "${CODEX_ROOT}"
  if [[ -f "${CODEX_CONFIG}" ]]; then
    BACKUP="${CODEX_CONFIG}.backup.$(date +%Y%m%d%H%M%S).$$"
    cp "${CODEX_CONFIG}" "${BACKUP}"
    echo "Backed up existing Codex config to ${BACKUP}"
  else
    : > "${CODEX_CONFIG}"
  fi
  if ! grep -q "parts-product-selection:begin" "${CODEX_CONFIG}"; then
    {
      printf '\n# parts-product-selection:begin\n'
      cat "${CONFIG_DIR}/mcp.toml"
      printf '# parts-product-selection:end\n'
    } >> "${CODEX_CONFIG}"
    echo "Added Meta and WordPress MCP entries to ${CODEX_CONFIG}"
  else
    echo "Existing parts-product-selection MCP block detected; config was not duplicated."
  fi
fi

echo
echo "Installed MCP files under: ${INSTALL_ROOT}"
echo "Generated config: ${CONFIG_DIR}/mcp.toml"
echo "Next: run ${INSTALL_ROOT}/configure-keychain.sh"
echo "Then: run ${INSTALL_ROOT}/doctor.sh"
if [[ "${APPLY_CONFIG}" -eq 0 ]]; then
  echo "To apply the config automatically, rerun this installer with --apply-config."
fi
